# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


#relative_permalinks: true

# Setup
title:               Syee's blog
tagline:             'Machine Learning/Deep Learning Engineer'
description:         "Syee's blog"
url:                 https://MrSyee.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              KIM KYUNG HWAN
  url:               https://MrSyee.github.io
  email:             khsyee@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/MrSyee'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
